name: CI

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
           node-version: 16

      - name: Installs dependecies and builds the website
        run: |
          npm install
          npm run build

      - name: Stores the build folder as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build artifacts
          path: build/

  test_website:
    runs-on: ubuntu-latest
    needs: [build_website]
    steps:
      - uses: actions/checkout@v3

      - name: Download the artifacts
        uses: actions/download-artifact@v3
        with:
          name: build artifacts
          path: build

      - name: Tests if manifest.json is available in build folder
        run: test -f build/manifest.json

  unit_tests:
    runs-on: ubuntu-latest
    needs: [build_website]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
           node-version: 16
      
      - name: Install dependecies and perform test
        run: |
          npm install
          npm t

       
